
package javastudy.supercalculator;

/**
 *
 * @author Victor
 */
public class ScreenSuperCalculator extends javax.swing.JFrame {

    /**
     * Creates new form ScreenSuperCalculator
     */
    public ScreenSuperCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSpinner = new javax.swing.JSpinner();
        btnCalculate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblRestTwo = new javax.swing.JLabel();
        lblCube = new javax.swing.JLabel();
        lblSquareRoot = new javax.swing.JLabel();
        lblCubeRoot = new javax.swing.JLabel();
        lblAbsoluteValue = new javax.swing.JLabel();
        imageCalculator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Super calculator");

        jLabel2.setText("Put a value:");

        txtSpinner.setModel(new javax.swing.SpinnerNumberModel());

        btnCalculate.setBackground(new java.awt.Color(157, 115, 191));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setToolTipText("");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel3.setText("Rest division for 2");

        jLabel4.setText("Cube");

        jLabel5.setText("Square root");
        jLabel5.setToolTipText("");

        jLabel6.setText("Cube root");

        jLabel7.setText("Absolute value");

        lblRestTwo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRestTwo.setForeground(new java.awt.Color(157, 115, 191));
        lblRestTwo.setText("0");

        lblCube.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCube.setForeground(new java.awt.Color(157, 115, 191));
        lblCube.setText("0");

        lblSquareRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSquareRoot.setForeground(new java.awt.Color(157, 115, 191));
        lblSquareRoot.setText("0");

        lblCubeRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCubeRoot.setForeground(new java.awt.Color(157, 115, 191));
        lblCubeRoot.setText("0");

        lblAbsoluteValue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAbsoluteValue.setForeground(new java.awt.Color(157, 115, 191));
        lblAbsoluteValue.setText("0");

        imageCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator-pixel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCubeRoot, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSquareRoot, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCube, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRestTwo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAbsoluteValue, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(imageCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalculate)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCalculate))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(imageCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRestTwo)
                                    .addGap(12, 12, 12)
                                    .addComponent(lblCube)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblSquareRoot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCubeRoot))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(lblAbsoluteValue)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Create a spinnerValue get value
        int spinnerValue = Integer.parseInt(txtSpinner.getValue().toString());
        
        // Rest calcualte
        int restDivision = spinnerValue % 2;
        lblRestTwo.setText(Integer.toString(restDivision));
        
        // Cube calculate
        double cube = (double) Math.pow(spinnerValue, 3);
        lblCube.setText(Double.toString(cube));
        
        // SquareRoot calulate and conditions
        double squareRoot = (double) Math.sqrt(spinnerValue);
        if (spinnerValue > 0 ){
            lblSquareRoot.setText(String.format("%.2f",squareRoot));
        }
        else if (spinnerValue == 0 | spinnerValue < 0){
            lblSquareRoot.setText("NaN");
        }
        
        double cubeRoot = (double) Math.cbrt(spinnerValue);
        lblCubeRoot.setText(String.format("%.4f",cubeRoot));
        
        int absoluteValue = Math.abs(spinnerValue);
        lblAbsoluteValue.setText(Integer.toString(absoluteValue));
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenSuperCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenSuperCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenSuperCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenSuperCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenSuperCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel imageCalculator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAbsoluteValue;
    private javax.swing.JLabel lblCube;
    private javax.swing.JLabel lblCubeRoot;
    private javax.swing.JLabel lblRestTwo;
    private javax.swing.JLabel lblSquareRoot;
    private javax.swing.JSpinner txtSpinner;
    // End of variables declaration//GEN-END:variables
}
