
package javastudy.genieofthelamp;

import java.util.Random;

/**
 *
 * @author Victor
 */
public class ScreenGenieLamp extends javax.swing.JFrame {

    // Create random number (0-5)
         
   
    public ScreenGenieLamp() {
        initComponents();
        lblThinking.setText("<html>I'm thinking of a value from <strong>0 to 5</strong>. Try to guess what that value is.</html>");
        jTrophy.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTrophy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblThinking = new javax.swing.JLabel();
        jSpinner = new javax.swing.JSpinner();
        btnChose = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTrophy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trophy.png"))); // NOI18N
        getContentPane().add(jTrophy, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel2.setText("Value:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/genie.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 320, 279));

        lblThinking.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        lblThinking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThinking.setText("thinking...");
        getContentPane().add(lblThinking, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 160, 100));

        jSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        getContentPane().add(jSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 87, -1));

        btnChose.setBackground(new java.awt.Color(157, 115, 191));
        btnChose.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnChose.setForeground(new java.awt.Color(255, 255, 255));
        btnChose.setText("Chose");
        btnChose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoseActionPerformed(evt);
            }
        });
        getContentPane().add(btnChose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 94, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thinkbubble.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoseActionPerformed
        // TODO add your handling code here:
        int spinnerNumber = Integer.parseInt(jSpinner.getValue().toString());
        Random randomNumber = new Random();
        int number = randomNumber.nextInt(5);  
        
        
        if (spinnerNumber == number){
            lblThinking.setText("<html><strong>You got it right</strong></html>");
            jTrophy.setVisible(true);
        }
        else{
            lblThinking.setText("<html>you were wrong!<br>I thought:  <html>"+number);
            jTrophy.setVisible(false);
        }
    }//GEN-LAST:event_btnChoseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenGenieLamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenGenieLamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenGenieLamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenGenieLamp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenGenieLamp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JLabel jTrophy;
    private javax.swing.JLabel lblThinking;
    // End of variables declaration//GEN-END:variables
}
