/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javastudy.triangleproject;

/**
 *
 * @author Victor
 */
public class ScreenTriangle extends javax.swing.JFrame {

    /**
     * Creates new form ScreenTriangle
     */
    public ScreenTriangle() {
        initComponents();
        jPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SliderA = new javax.swing.JSlider();
        SliderB = new javax.swing.JSlider();
        SliderC = new javax.swing.JSlider();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblATriangle = new javax.swing.JLabel();
        lblBTriangle = new javax.swing.JLabel();
        lblCTriangle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        lblForm = new javax.swing.JLabel();
        lblTriangle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("<html><strong>A</strong><html> value");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 44, -1, -1));

        jLabel2.setText("<html><strong>B</strong><html> value");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 84, -1, -1));

        jLabel3.setText("<html><strong>C</strong><html> value");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 126, -1, -1));

        SliderA.setBackground(new java.awt.Color(255, 204, 0));
        SliderA.setMaximum(20);
        SliderA.setToolTipText("");
        SliderA.setValue(0);
        SliderA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderAStateChanged(evt);
            }
        });
        getContentPane().add(SliderA, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 42, 150, -1));

        SliderB.setBackground(new java.awt.Color(255, 204, 0));
        SliderB.setMaximum(20);
        SliderB.setToolTipText("");
        SliderB.setValue(0);
        SliderB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderBStateChanged(evt);
            }
        });
        getContentPane().add(SliderB, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 82, 150, -1));

        SliderC.setBackground(new java.awt.Color(255, 204, 0));
        SliderC.setMaximum(20);
        SliderC.setToolTipText("");
        SliderC.setValue(0);
        SliderC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderCStateChanged(evt);
            }
        });
        getContentPane().add(SliderC, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 124, 150, -1));

        lblA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblA.setText("0");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 44, -1, -1));

        lblB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblB.setText("0");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 84, -1, -1));

        lblC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblC.setText("0");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 126, -1, -1));

        lblATriangle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblATriangle.setText("a");
        getContentPane().add(lblATriangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        lblBTriangle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblBTriangle.setText("b");
        getContentPane().add(lblBTriangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        lblCTriangle.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblCTriangle.setForeground(new java.awt.Color(0, 0, 0));
        lblCTriangle.setText("c");
        getContentPane().add(lblCTriangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/triangle.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 214, -1));

        btnCheck.setBackground(new java.awt.Color(255, 204, 0));
        btnCheck.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));

        lblForm.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblForm.setForeground(new java.awt.Color(0, 0, 0));
        lblForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForm.setText("Form or not?");

        lblTriangle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTriangle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTriangle.setText("Type of triangle");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTriangle, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblForm)
                .addGap(18, 18, 18)
                .addComponent(lblTriangle)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        jPanel.setVisible(true);

        int a = SliderA.getValue();
        int b = SliderB.getValue();
        int c = SliderC.getValue();

        if (a < b + c && b < a + c && c < a + b) {
            lblForm.setText("Form a triangle");
            if (a == b && b == c) {
                lblTriangle.setText("Equilateral");
            } else if (a != b && b != c && a != c) {
                lblTriangle.setText("Scalene");
            } else {
                lblTriangle.setText("Isosceles");
            }
        } else {
            lblForm.setText("Dont form a triangle");
            lblTriangle.setText("------------");
        }

    }//GEN-LAST:event_btnCheckActionPerformed

    private void SliderAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderAStateChanged
        // TODO add your handling code here:
        lblA.setText(Integer.toString(SliderA.getValue()));
        lblATriangle.setText(Integer.toString(SliderA.getValue()));
    }//GEN-LAST:event_SliderAStateChanged

    private void SliderBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderBStateChanged
        // TODO add your handling code here:
        lblB.setText(Integer.toString(SliderB.getValue()));
        lblBTriangle.setText(Integer.toString(SliderB.getValue()));
    }//GEN-LAST:event_SliderBStateChanged

    private void SliderCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderCStateChanged
        // TODO add your handling code here:
        lblC.setText(Integer.toString(SliderC.getValue()));
        lblCTriangle.setText(Integer.toString(SliderC.getValue()));
    }//GEN-LAST:event_SliderCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenTriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenTriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SliderA;
    private javax.swing.JSlider SliderB;
    private javax.swing.JSlider SliderC;
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblATriangle;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblBTriangle;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCTriangle;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblTriangle;
    // End of variables declaration//GEN-END:variables
}
